////
//// NOTE: THIS FILE IS AUTO-GENERATED by the "ExtensionsGenerator".kt
//// See: https://github.com/tdlibx/td-ktx-generator/
////
//package kotlinx.telegram.extensions
//
//import com.saer.api.extensions.BasicGroupKtx
//import com.saer.api.extensions.CallKtx
//import com.saer.api.extensions.ChatKtx
//import com.saer.api.extensions.CommonKtx
//import kotlinx.telegram.core.TelegramFlow
//
///**
// * Interface for access all Telegram objects extension functions. Contains 182 extensions
// */
//interface TelegramKtx : BasicGroupKtx, CallKtx, ChatKtx, FileKtx, MessageKtx, NotificationGroupKtx,
//    ProxyKtx, SecretChatKtx, SupergroupKtx, UserKtx, CommonKtx {
//  /**
//   * Instance of the [TelegramFlow] connecting extensions to the Telegram Client
//   */
//  override val api: TelegramFlow
//}
